data:
    benchmark: "benchmarks/benchmark_ecg2.yaml"
    dataset_dir: "datasets/dataset_ecg_fitness"
    output_dir: "output/final_exp1_ecg_new2_split2"

models:
    extractor_model_path: "Models/extractor_model5.py"
    estimator_model_path: "Models/estimator_model.py"

weights:
    extractor_weights: "output/final_exp1_pure_new_model_split1_good/best_extractor_weights.pth"
    estimator_weights: "output/final_exp1_ecg_new2_split2/best_estimator_weights.pth"

save_predictions_to_txt: True

dataset_options:
    sequence_length: 300
    shift: 300