data:
    benchmark: "benchmarks/benchmark_pure.yaml"
    dataset_dir: "/mnt/data_personal/mikolond/datasets/pure_extractor_dataset"
    output_dir: "output/pure_latent3_exp4/"

optimizer:
    batch_size: 1
    cumulative_batch_size: 50
    lr: 1e-5
    max_epochs: 600
    patience: 150
    decrease_lr: False
    lr_decay: 0.3
    lr_decay_epochs: [20, 50, 80, 100]

hr_data:
    frequency_range: [40, 240]
    delta: 5
    sampling_frequency: 1

train:
    sequence_length: 150
    shift: 100
    augment: True

valid:
    sequence_length: 150
    shift: 150
    augment: False

load_model: False
load_model_path: "output/weights/synthetic/extractor/epoch_150.pth"