data:
    benchmark: "benchmarks/benchmark_pure.yaml"
    dataset_dir: "/mnt/data_personal/mikolond/datasets/pure_extractor_dataset"
    output_dir: "output/pure_latent_extractor_exp6/"

optimizer:
    batch_size: 1
    cumulative_batch_size: 30
    lr: 1e-4
    max_epochs: 600
    patience: 60
    decrease_lr: False
    lr_decay: 0.1
    lr_decay_epochs: [100, 200]

hr_data:
    frequency_range: [40, 240]
    delta: 5
    sampling_frequency: 1

train:
    sequence_length: 300
    shift: 150
    augment: True

valid:
    sequence_length: 300
    shift: 300
    augment: False

load_model: True
load_model_path: "output/pure_latent_extractor_exp3/best_extractor_weights.pth"