data:
    benchmark: "benchmarks/benchmark_pure.yaml"
    dataset_dir: "/mnt/data_personal/mikolond/datasets/pure_extractor_dataset"
    output_dir: "output/pure_segment_exp2/"

extractor_model_path: "Models/extractor_model_segment.py"

optimizer:
    batch_size: 3
    cumulative_batch_size: 17
    lr: 1e-4
    max_epochs: 600
    patience: 150
    decrease_lr: True
    lr_decay: 0.3
    lr_decay_epochs: [50, 100]

hr_data:
    frequency_range: [40, 240]
    delta: 5
    sampling_frequency: 1

train:
    sequence_length: 150
    shift: 150
    augment: True

valid:
    sequence_length: 150
    shift: 150
    augment: False

load_model: False
load_model_path: "output/weights/synthetic/extractor/epoch_150.pth"

# changed model a bit just resize insteada of max and avg pooling
