data:
    benchmark: "benchmarks/benchmark_pure.yaml"
    dataset_dir: "datasets/dataset_pure"
    output_dir: "output/pure_exp12_best"

weights:
    extractor_weights: "output/pure_exp12/best_extractor_weights.pth"
    estimator_weights: "output/pure_exp12_best/best_estimator_weights.pth"

dataset_options:
    sequence_length: 300
    shift: 300