data:
    benchmark: "benchmarks/benchmark_ecg2.yaml"
    dataset_dir: "datasets/dataset_ecg_fitness"
    output_dir: "output/model3_exp1_ecg"

extractor_model_path: "Models/extractor_model4.py"
estimator_model_path: "Models/estimator_model2.py"

weights:
    extractor_weights: "output/extractor_model3_exp1/best_extractor_weights.pth"
    estimator_weights: "output/model3_exp1_ecg/best_estimator_weights.pth"

dataset_options:
    sequence_length: 300
    shift: 300