data:
    benchmark: "benchmarks/benchmark_pure.yaml"
    dataset_dir: "datasets/dataset_pure"
    output_dir: "output/pure_decreasing_test"

weights:
    extractor_weights: "output/weights/pure_decreasing/best_extractor_weights.pth"
    estimator_weights: "output/pure_decreasing_test/best_estimator_weights.pth"

dataset_options:
    sequence_length: 300
    shift: 300