data:
    benchmark: "benchmarks/benchmark_pure.yaml"
    dataset_dir: "datasets/dataset_pure"
    output_dir: "output/extractor_model2_exp1"

extractor_model_path: "Models/extractor_model2.py"

optimizer:
    batch_size: 1
    cumulative_batch_size: 50
    lr: 1e-3
    max_epochs: 600
    patience: 150
    decrease_lr: True
    lr_decay: 0.1
    lr_decay_epochs: [20, 50]

hr_data:
    frequency_range: [40, 240]
    delta: 5
    sampling_frequency: 1

train:
    sequence_length: 150
    shift: 150
    augment: True

valid:
    sequence_length: 150
    shift: 150
    augment: False

load_model: False
load_model_path: "output/weights/synthetic/extractor/epoch_150.pth"