data:
    benchmark: "benchmarks/benchmark_pure.yaml"
    dataset_dir: "datasets/dataset_pure"
    output_dir: "output/pure_local_latent3_exp1/"

optimizer:
    batch_size: 1
    cumulative_batch_size: 50
    lr: 1e-4
    max_epochs: 600
    patience: 150
    decrease_lr: True
    lr_decay: 0.5
    lr_decay_epochs: [15, 50, 80, 100]

hr_data:
    frequency_range: [40, 240]
    delta: 5
    sampling_frequency: 1

train:
    sequence_length: 150
    shift: 100
    augment: True

valid:
    sequence_length: 150
    shift: 150
    augment: False

load_model: True
load_model_path: "output/pure_exp1_local_test2/best_extractor_weights.pth"