data:
    benchmark: "benchmarks/benchmark_ecg2.yaml"
    dataset_dir: "datasets/dataset_ecg_fitness"
    output_dir: "output/model3_exp1_ecg"

extractor_model_path: "Models/extractor_model4.py"

optimizer:
    batch_size: 1
    cumulative_batch_size: 100
    lr: 1e-6
    max_epochs: 600
    patience: 150
    decrease_lr: True
    lr_decay: 0.1
    lr_decay_epochs: [20,50,150]

hr_data:
    frequency_range: [40, 240]
    delta: 5
    sampling_frequency: 1

train:
    sequence_length: 150
    shift: 150
    augment: True

valid:
    sequence_length: 150
    shift: 150
    augment: False

load_model: True
load_model_path: "output/extractor_model3_exp1/best_extractor_weights.pth"