data:
    benchmark: "benchmarks/benchmark_pure.yaml"
    extractor_dataset_dir: "datasets/dataset_pure"
    extractor_weights: "output/pure_exp24/best_extractor_weights.pth"
    estimator_dataset_dir: "datasets/estimator_pure_exp24"
    output_dir: "output/pure_exp24_new4"

extractor_model_path: "Models/extractor_model.py"
estimator_model_path: "Models/estimator_model.py"

optimizer:
    batch_size: 500
    lr: 0.05
    max_epochs: 5000
    patience: 400
    decrease_lr: False
    lr_decay: 0.1
    lr_decay_epochs: [50,100]

create_new_dataset: False
dataset_creator_N: 600
dataset_creator_augmentation: False

train:
    sequence_length: 300
    shift: 50

valid:
    sequence_length: 300
    shift: 300

epochs_to_new_dataset: 100

load_model: False
load_model_path: "output/freq_preset/best_estimator_weights.pth"