data:
    benchmark: "benchmarks/benchmark_pure.yaml"
    dataset_dir: "datasets/dataset_pure"
    output_dir: "output/pure_local_latent3_exp1"

weights:
    extractor_weights: "output/pure_local_latent3_exp1/best_extractor_weights.pth"
    estimator_weights: "output/pure_local_latent3_exp1/best_estimator_weights.pth"

dataset_options:
    sequence_length: 150
    shift: 150