data:
    benchmark: "benchmarks/benchmark_ecg2.yaml"
    extractor_dataset_dir: "datasets/dataset_ecg_fitness"
    extractor_weights: "output/extractor_model2_exp1/best_extractor_weights.pth"
    estimator_dataset_dir: "datasets/estimator_ecg_model2"
    output_dir: "output/extractor_model2_exp1/ecg_estimator"

extractor_model_path: "Models/extractor_model2.py"
estimator_model_path: "Models/estimator_model2.py"

optimizer:
    batch_size: 600
    lr: 0.01
    max_epochs: 5000
    patience: 250
    decrease_lr: True
    lr_decay: 0.3
    lr_decay_epochs: [50,100]

create_new_dataset: False
dataset_creator_N: 600
dataset_creator_augmentation: False

train:
    sequence_length: 300
    shift: 50

valid:
    sequence_length: 300
    shift: 300

epochs_to_new_dataset: 100

load_model: False
load_model_path: "output/weights/synthetic/extractor/epoch_150.pth"