data:
    benchmark: "benchmarks/benchmark_pure.yaml"
    extractor_dataset_dir: "datasets/dataset_pure"
    extractor_weights: "output/pure_exp15/best_extractor_weights.pth"
    estimator_dataset_dir: "datasets/estimator_pure_exp15_best"
    output_dir: "output/pure_exp15_best"

optimizer:
    batch_size: 1000
    lr: 0.001
    max_epochs: 1000
    patience: 150
    decrease_lr: True
    lr_decay: 0.2
    lr_decay_epochs: [100,200, 400, 600]

create_new_dataset: True
dataset_creator_N: 600
dataset_creator_augmentation: True

train:
    sequence_length: 300
    shift: 20

valid:
    sequence_length: 300
    shift: 300

epochs_to_new_dataset: 100

load_model: True
load_model_path: "output/pure_exp15_best/best_estimator_weights.pth"