data:
    benchmark: "benchmarks/benchmark_pure.yaml"
    extractor_dataset_dir: "datasets/dataset_pure"
    extractor_weights: "output/final_exp1_pure_new_model/best_extractor_weights.pth"
    estimator_dataset_dir: "datasets/final_exp1_pure_new_model"
    output_dir: "output/final_exp1_pure_original_model"

extractor_model_path: "Models/extractor_model4.py"
estimator_model_path: "Models/estimator_model.py"

optimizer:
    batch_size: 600
    lr: 0.1
    max_epochs: 5000
    patience: 300
    decrease_lr: True
    lr_decay: 0.1
    lr_decay_epochs: [100]

create_new_dataset: False
dataset_creator_N: 600
dataset_creator_augmentation: False

train:
    sequence_length: 300
    shift: 50

valid:
    sequence_length: 300
    shift: 300

epochs_to_new_dataset: 100

load_model: False
load_model_path: "output/weights/synthetic/extractor/epoch_150.pth"