data:
    benchmark: "benchmarks/benchmark_pure.yaml"
    dataset_dir: "datasets/dataset_pure"
    output_dir: "output/final_exp1_pure_new_model"

models:
    extractor_model_path: "Models/extractor_model4.py"
    estimator_model_path: "Models/estimator_model_smaller.py"

weights:
    extractor_weights: "output/final_exp1_pure_new_model/best_extractor_weights.pth"
    estimator_weights: "output/final_exp1_pure_new_model/best_estimator_weights.pth"

save_predictions_to_txt: True

dataset_options:
    sequence_length: 300
    shift: 300