data:
    benchmark: "benchmarks/benchmark_ecg2.yaml"
    dataset_dir: "datasets/dataset_ecg_fitness"
    output_dir: "output/pure_model5_exp1_ecg"

models:
    extractor_model_path: "Models/extractor_model5.py"
    estimator_model_path: "Models/estimator_model.py"

weights:
    extractor_weights: "output/ecg_model5_exp1/best_extractor_weights.pth"
    estimator_weights: "output/pure_model5_exp1_ecg/best_estimator_weights.pth"

save_predictions_to_txt: True

dataset_options:
    sequence_length: 300
    shift: 300