data:
    benchmark: "benchmarks/benchmark_pure2.yaml"
    dataset_dir: "/ssd/temporary/mikolond/datasets/pure_extractor_dataset"
    output_dir: "output/final_exp1_pure_new_model_split2"

extractor_model_path: "Models/extractor_model5.py"

optimizer:
    batch_size: 1
    cumulative_batch_size: 100
    lr: 1e-4
    max_epochs: 600
    patience: 50
    decrease_lr: False
    lr_decay: 0.1
    lr_decay_epochs: [20,50,150]

hr_data:
    frequency_range: [40, 240]
    delta: 5
    sampling_frequency: 1

train:
    sequence_length: 150
    shift: 150
    augment: True

valid:
    sequence_length: 150
    shift: 150
    augment: False

load_model: False
load_model_path: "output/extractor_model3_exp1/last_extractor_weights.pth"