data:
    benchmark: "benchmarks/benchmark_debug_synthetic.yaml"
    dataset_dir: "datasets/dataset_synthetic/"
    output_dir: "output/synthetic_new2/"

extractor_model_path: "Models/extractor_latent7.py"

optimizer:
    batch_size: 1
    cumulative_batch_size: 30
    lr: 1e-2
    max_epochs: 40
    patience: 5
    decrease_lr: True
    lr_decay: 0.2
    lr_decay_epochs: [5, 10]

hr_data:
    frequency_range: [40, 240]
    delta: 5
    sampling_frequency: 1

train:
    sequence_length: 150
    shift: 150
    augment: True

valid:
    sequence_length: 150
    shift: 150
    augment: False

load_model: False
load_model_path: "output/weights/synthetic/extractor/epoch_150.pth"