data:
    benchmark: "benchmarks/benchmark_debug_synthetic.yaml"
    extractor_dataset_dir: "datasets/dataset_synthetic/"
    extractor_weights: "output/synthetic_new/output/synthetic_new/best_extractor_weights.pth"
    estimator_dataset_dir: "datasets/estimator_synthetic/"
    output_dir: "output/synthetic_new/"

optimizer:
    batch_size: 400
    lr: 0.1
    max_epochs: 600
    patience: 200
    decrease_lr: True
    lr_decay: 0.6
    lr_decay_epochs: [200,300]

create_new_dataset: True
dataset_creator_N: 600
dataset_creator_augmentation: False

train:
    sequence_length: 300
    shift: 50

valid:
    sequence_length: 300
    shift: 300

epochs_to_new_dataset: 100

load_model: False
load_model_path: "output/weights/synthetic/extractor/epoch_150.pth"