data:
    benchmark: "benchmarks/benchmark_debug_synthetic.yaml"
    dataset_dir: "datasets/dataset_synthetic/"
    output_dir: "output/synthetic_new/"

weights:
    extractor_weights: "output/synthetic_new/best_extractor_weights.pth"
    estimator_weights: "output/synthetic_new/best_estimator_weights.pth"

dataset_options:
    sequence_length: 300
    shift: 300