data:
    benchmark: "benchmarks/benchmark_debug_synthetic.yaml"
    dataset_dir: "datasets/dataset_synthetic/"
    output_dir: "output/synthetic_new3/"

optimizer:
    batch_size: 1
    cumulative_batch_size: 50
    lr: 1e-4
    max_epochs: 40
    patience: 5
    decrease_lr: True
    lr_decay: 0.1
    lr_decay_epochs: [2,5, 10]

hr_data:
    frequency_range: [40, 240]
    delta: 5
    sampling_frequency: 1

train:
    sequence_length: 150
    shift: 150
    augment: True

valid:
    sequence_length: 150
    shift: 150
    augment: False

load_model: True
load_model_path: "output/synthetic_new2/best_extractor_weights.pth"