data:
    benchmark: "benchmarks/benchmark_pure.yaml"
    dataset_dir: "datasets/pure_extractor_dataset/"
    output_dir: "output/results/"
    weights_dir: "output/weights_pure/"
extractor:
    optimizer:
        batch_size: 1
        cumulative_batch_size: 1
        lr: 1e-4
        max_epochs: 300
        patience: 50
        decrease_lr: False
        lr_decay: 0.5
        lr_decay_epochs: [5, 15,15]

    hr_data:
        frequency_range: [40, 240]
        delta: 5
        sampling_frequency: 1

    train:
        sequence_length: 300
        shift: 150
        augment: True

    valid:
        sequence_length: 300
        shift: 300
        augment: False
estimator:
    optimizer:
        batch_size: 2
        lr: 0.01
        max_epochs: 300
        patience: 50
        decrease_lr: False
        lr_decay: 0.5
        lr_decay_epochs: [5, 15,15]
    train:
        sequence_length: 300
        shift: 100
        augment: True
    valid:
        sequence_length: 300
        shift: 300
        augment: False