data:
    benchmark: "benchmarks/benchmark_ecg.yaml"
    dataset_dir: "datasets/dataset_ecg_fitness/"
    output_dir: "output/results/"
    weights_dir: "output/weights_median_1e-4_cum_40/"

optimizer:
    batch_size: 1
    cumulative_batch_size: 40
    lr: 1e-4
    num_epochs: 30
    decrease_lr: False
    lr_decay: 0.5
    lr_decay_epochs: [5, 15,15]

hr_data:
    frequency_range: [40, 240]
    delta: 5
    sampling_frequency: 1

train:
    sequence_length: 300
    shift: 150
    augment: False

valid:
    sequence_length: 300
    shift: 300
    augment: False
