data:
    benchmark: "benchmarks/benchmark_pure.yaml"
    dataset_dir: "/mnt/data_personal/mikolond/datasets/dataset_ecg_fitness"
    output_dir: "output/results/ecg_1e-5_150"
    weights_dir: "output/weights/ecg_1e-5_150"
extractor:
    optimizer:
        batch_size: 8
        cumulative_batch_size: 50
        lr: 1e-5
        max_epochs: 400
        patience: 80
        decrease_lr: False
        lr_decay: 0.1
        lr_decay_epochs: [10, 30,80]

    hr_data:
        frequency_range: [40, 240]
        delta: 5
        sampling_frequency: 1

    train:
        sequence_length: 150
        shift: 150
        augment: True

    valid:
        sequence_length: 300
        shift: 300
        augment: False
estimator:
    optimizer:
        batch_size: 200
        lr: 0.01
        max_epochs: 600
        patience: 80
        decrease_lr: False
        lr_decay: 0.5
        lr_decay_epochs: [5, 15,15]
    train:
        sequence_length: 300
        shift: 100
        augment: True
    valid:
        sequence_length: 300
        shift: 300
        augment: False
