data:
    benchmark: "benchmarks/benchmark_example.yaml"
    extractor_dataset_dir: "path/to/extractor_dataset"
    extractor_weights: "path/to/extractor_weights.pth"
    estimator_dataset_dir: "path/to/estimator_dataset" # path where the new estimatr dataset will be created using extractor dataset and trained weights
    output_dir: "path/to/output"

extractor_model_path: "Models/extractor_model.py"
estimator_model_path: "Models/estimator_model.py"

optimizer:
    batch_size: 600
    lr: 0.1
    max_epochs: 5000
    patience: 300
    decrease_lr: True
    lr_decay: 0.1
    lr_decay_epochs: [100]

create_new_dataset: False
dataset_creator_N: 600
dataset_creator_augmentation: False

train:
    sequence_length: 300
    shift: 50

valid:
    sequence_length: 300
    shift: 300

load_model: False
load_model_path: "path/to/weights.pth"