data:
    benchmark: "benchmarks/benchmark_synthetic.yaml"
    dataset_dir: "datasets/dataset_synthetic/"
    output_dir: "output/results/"
    weights_dir: "output/weights/"

optimizer:
    batch_size: 1
    cumulative_batch_size: 1
    lr: 1e-3
    num_epochs: 10
    decrease_lr: True
    lr_decay: 0.1
    lr_decay_epochs: [5, 8]

hr_data:
    frequency_range: [40, 240]
    delta: 5
    sampling_frequency: 1

train:
    sequence_length: 150
    shift: 150
    augment: True

valid:
    sequence_length: 150
    shift: 150
    augment: False