data:
    benchmark: "benchmarks/benchmark_example.yaml"
    dataset_dir: "path/to/dataset"
    output_dir: "path/to/output"

extractor_model_path: "Models/extractor_model.py"

optimizer:
    batch_size: 1
    cumulative_batch_size: 100
    lr: 1e-3
    max_epochs: 600
    patience: 200
    decrease_lr: True
    lr_decay: 0.1
    lr_decay_epochs: [20,50,150, 200]

hr_data:
    frequency_range: [40, 240]
    delta: 5
    sampling_frequency: 1

train:
    sequence_length: 150
    shift: 150
    augment: True

valid:
    sequence_length: 150
    shift: 150
    augment: False

load_model: False
load_model_path: "path/to/weights.pth"