data:
    benchmark: "benchmarks/benchmark_debug_synthetic.yaml"
    dataset_dir: "datasets/dataset_synthetic/"
    output_dir: "output/results/debug/"
    weights_dir: "output/weights/debug/"

extractor:
    optimizer:
        batch_size: 1
        cumulative_batch_size: 1
        lr: 5e-2
        max_epochs: 10
        patience: 2
        decrease_lr: False
        lr_decay: 0.25
        lr_decay_epochs: [5, 10, 15, 25]

    hr_data:
        frequency_range: [40, 240]
        delta: 5
        sampling_frequency: 1

    train:
        sequence_length: 150
        shift: 150
        augment: True

    valid:
        sequence_length: 150
        shift: 150
        augment: False
estimator:
    optimizer:
        batch_size: 100
        lr: 0.1
        max_epochs: 300
        patience: 50
        decrease_lr: False
        lr_decay: 0.5
        lr_decay_epochs: [5, 15,15]

    train:
        sequence_length: 300
        shift: 300
        augment: True

    valid:
        sequence_length: 300
        shift: 300
        augment: False