data:
    benchmark: "benchmarks/benchmark_synthetic.yaml"
    dataset_dir: "datasets/dataset_synthetic/"
    output_dir: "output/results/"
    weights_dir: "output/weights/"

optimizer:
    batch_size: 1
    cumulative_batch_size: 1
    lr: 1e-5
    num_epochs: 15
    decrease_lr: False
    lr_decay: 0.25
    lr_decay_epochs: [5, 10, 15, 25]

hr_data:
    frequency_range: [40, 240]
    delta: 3
    sampling_frequency: 0.5

train:
    sequence_length: 150
    shift: 50
    augment: True

valid:
    sequence_length: 150
    shift: 150
    augment: False