models:
  extractor_model_path: "Models/extractor_model4.py"
  estimator_model_path: "Models/estimator_model.py"
weights:
  extractor_weights: "output/final_exp1_pure_new_model/best_extractor_weights.pth"
  estimator_weights: "output/final_exp1_pure_new_model/best_estimator_weights.pth"

video_path: "test_videos/me_70_phone.mp4"
output_dir: "output/processed_videos"
