data:
    benchmark: "benchmarks/benchmark_pure.yaml"
    dataset_dir: "/mnt/data_personal/mikolond/datasets/pure_extractor_dataset"
    output_dir: "output/results/pure_1e-4"
    weights_dir: "output/weights/pure_1e-4"
extractor:
    optimizer:
        batch_size: 1
        cumulative_batch_size: 100
        lr: 1e-4
        max_epochs: 500
        patience: 60
        decrease_lr: False
        lr_decay: 0.5
        lr_decay_epochs: [5, 15,15]

    hr_data:
        frequency_range: [40, 240]
        delta: 5
        sampling_frequency: 1

    train:
        sequence_length: 300
        shift: 50
        augment: True

    valid:
        sequence_length: 300
        shift: 300
        augment: False
estimator:
    optimizer:
        batch_size: 300
        lr: 0.01
        max_epochs: 700
        patience: 100
        decrease_lr: False
        lr_decay: 0.5
        lr_decay_epochs: [5, 15,15]
    train:
        sequence_length: 300
        shift: 100
        augment: True
    valid:
        sequence_length: 300
        shift: 300
        augment: False
