data:
    benchmark: "benchmarks/benchmark_pure.yaml"
    dataset_dir: "datasets/pure_extractor_dataset"
    output_dir: "output/results/pure_decreasing"
    weights_dir: "output/weights/pure_decreasing"
extractor:
    optimizer:
        batch_size: 1
        cumulative_batch_size: 100
        lr: 1e-3
        max_epochs: 300
        patience: 50
        decrease_lr: True
        lr_decay: 0.1
        lr_decay_epochs: [20, 50,80]

    hr_data:
        frequency_range: [40, 240]
        delta: 5
        sampling_frequency: 1

    train:
        sequence_length: 150
        shift: 150
        augment: True

    valid:
        sequence_length: 300
        shift: 300
        augment: False
