data:
    benchmark: "benchmarks/benchmark_pure.yaml"
    extractor_dataset_dir: "datasets/dataset_pure"
    extractor_weights: "output/weights/pure_decreasing/best_extractor_weights.pth"
    estimator_dataset_dir: "datasets/estimator_pure_decreasing_aug/"
    output_dir: "output/pure_decreasing_aug_4/"

optimizer:
    batch_size: 500
    lr: 0.001
    max_epochs: 600
    patience: 200
    decrease_lr: True
    lr_decay: 0.6
    lr_decay_epochs: [200,300]

create_new_dataset: False
dataset_creator_N: 600
dataset_creator_augmentation: True

train:
    sequence_length: 300
    shift: 5

valid:
    sequence_length: 300
    shift: 50

epochs_to_new_dataset: 100

load_model: True
load_model_path: "output/pure_decreasing_aug_3/best_estimator_weights.pth"