data:
    benchmark: "benchmarks/benchmark_ecg2.yaml"
    dataset_dir: "/mnt/data_personal/mikolond/datasets/dataset_ecg_fitness"
    output_dir: "output/ecg_exp26_continue/"

model_path: "Models/extractor_model.py"

optimizer:
    batch_size: 1
    cumulative_batch_size: 100
    lr: 1e-5
    max_epochs: 600
    patience: 150
    decrease_lr: False
    lr_decay: 0.1
    lr_decay_epochs: [20, 50, 80, 100]

hr_data:
    frequency_range: [20, 240]
    delta: 8
    sampling_frequency: 1

train:
    sequence_length: 150
    shift: 150
    augment: True

valid:
    sequence_length: 150
    shift: 150
    augment: False

load_model: True
load_model_path: "output/ecg_exp26/last_extractor_weights.pth"

# training extractor on ecg fitness dataset