data:
    benchmark: "benchmarks/benchmark_pure.yaml"
    dataset_dir: "/mnt/data_personal/mikolond/datasets/pure_extractor_dataset"
    output_dir: "output/pure_exp4/"

optimizer:
    batch_size: 3
    cumulative_batch_size: 70
    lr: 1e-4
    max_epochs: 600
    patience: 100
    decrease_lr: True
    lr_decay: 0.1
    lr_decay_epochs: [20, 50, 80]

hr_data:
    frequency_range: [40, 240]
    delta: 5
    sampling_frequency: 1

train:
    sequence_length: 150
    shift: 50
    augment: True

valid:
    sequence_length: 150
    shift: 150
    augment: False

load_model: False
load_model_path: "output/weights/synthetic/extractor/epoch_150.pth"
