data:
    benchmark: "benchmarks/benchmark_pure.yaml"
    dataset_dir: "/mnt/data_personal/mikolond/datasets/pure_extractor_dataset"
    output_dir: "output/pure_exp18/"

optimizer:
    batch_size: 1
    cumulative_batch_size: 30
    lr: 1e-4
    max_epochs: 300
    patience: 50
    decrease_lr: False
    lr_decay: 0.1
    lr_decay_epochs: [20, 50, 80]

hr_data:
    frequency_range: [40, 240]
    delta: 5
    sampling_frequency: 1

train:
    sequence_length: 300
    shift: 150
    augment: False

valid:
    sequence_length: 300
    shift: 300
    augment: False

load_model: False
load_model_path: "output/weights/synthetic/extractor/epoch_150.pth"

# weight decay set to 0.01
